#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Laravel Localize', '1.0.0');
$command = new PawelMysior\LaravelLocalize\LocalizeCommand();

$app->add($command);

$app->setDefaultCommand($command->getName(), true);

$app->run();
